go:
  port: 8081
database:
  master:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: YOUR_DB_PASSWORD
    dbname: masterdb
    sslmode: disable
  worker:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: YOUR_DB_PASSWORD
    dbname: workerdb
    sslmode: disable
oidc:
  - tenancy: iam
    ClientID: iam
    ClientSecret: YOUR_CLIENT_SECRET
    issuer: http://iot.auth.localhost/realms/iot-customer
    jwks_url: http://iot.auth.localhost/realms/iot-customer/protocol/openid-connect/certs
