go:
  port: 8081
database:
  master:
    host: ${DB_MASTER_HOST}
    port: ${DB_MASTER_PORT}
    user: ${DB_MASTER_USER}
    password: ${DB_MASTER_PASSWORD}
    dbname: ${DB_MASTER_NAME}
    sslmode: ${DB_MASTER_SSL}
  worker:
    host: ${DB_WORKER_HOST}
    port: ${DB_WORKER_PORT}
    user: ${DB_WORKER_USER}
    password: ${DB_WORKER_PASSWORD}
    dbname: ${DB_WORKER_NAME}
    sslmode: ${DB_WORKER_SSL}
oidc:
  - tenancy: iam
    ClientID: iam
    ClientSecret: ${OIDC_CLIENT_SECRET}
    issuer: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
    jwks_url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs